Interfaces - chapter 8
LaunchCodeEducation/java-web-dev-curriculum pull request #12
Opened 2023-06-15 22:07 UTC by speudusa

2023-06-21 19:12 UTC, codinglikeagirl42 commented on content/interfaces/reading/abstract-classes/index.md
> +   ans: 1 and 3
Suggestion make the ans a comment.

2023-06-22 13:44 UTC, codinglikeagirl42 commented on content/interfaces/studio/index.md
> +   1. Extend the base class into the `CD` and `DVD` classes.
Formatting is off in this section due to placement of note, ordered list goes from 3 to 1 instead of four.

Also noticed that some ordered lists have extra spacing and others do not on this page. Suggest removing extra spacing from all lists.

2023-06-22 13:48 UTC, codinglikeagirl42 commented on content/interfaces/reading/interfaces/index.md
> +
Suggestion - remove extra spaces to match formatting of other ordered lists on page.

2023-06-22 13:53 UTC, codinglikeagirl42 commented on content/interfaces/reading/abstract-classes/index.md
> +   1. Interfaces may only contain implementation code inside of default or static methods. Therefore, interfaces can’t contain methods that need to be shared by class instances in the same way that a
Suggest remove extra spaces

2023-06-22 14:03 UTC, codinglikeagirl42 commented on content/interfaces/exercises/_index.md
> +Work on these exercises in the IntelliJ `java-web-dev-projects`. You will find the starter code in the `lsn7interfaces` package. Go ahead and open the folder and take a quick look at the class files.
Suggest updating name - java-web-dev-projects-17 
Also suggest removing extra spacing from ordered lists on the page.

2023-06-22 14:06 UTC, codinglikeagirl42 requested changes
Please address formatting issues and resubmit for review.

2023-07-14 15:00 UTC, jwoolbright23 approved these changes
Approving merge of textbook instructions.

2023-07-26 22:08 UTC, merged