Assignment 1
LaunchCodeEducation/java-web-dev-curriculum pull request #2
Opened 2023-05-24 15:47 UTC by jwoolbright23

2023-05-25 21:23 UTC, codinglikeagirl42 commented on content/assignments/techjobs-console/_index.md
> +or more of the [bonus missions](#tech-jobs-console-bonus-missions).
Please update link.

2023-05-25 21:23 UTC, codinglikeagirl42 commented on content/assignments/techjobs-console/_index.md
> +In Canvas, **Graded Assignment #1: TechJobs Console** contains a GitHub Classroom assignment invitation link and then set up the project in IntelliJ. Refer back to the GitHub Classroom instructions f
Please update link

2023-05-25 21:25 UTC, codinglikeagirl42 commented on content/assignments/techjobs-console/submission/index.md
> +[submission instructions]().
Please update link.

2023-05-25 21:29 UTC, codinglikeagirl42 commented on content/assignments/next-steps.md
> +lastMod: 2023-02-07  # UPDATE ANY TIME CHANGES ARE MADE
```suggestion
originalAuthor: John Woolbright # to be set by page creator
originalAuthorGitHub: jwoolbright23 # to be set by page creator
reviewer: Kimberly Horan # to be set by the page reviewer
reviewerGitHub: codinglikeagirl42 # to be set by the page reviewer
lastEditor:  # update any time edits are made after review
lastEditorGitHub:  # update any time edits are made after review
lastMod:   # UPDATE ANY TIME CHANGES ARE MADE
```

2023-05-25 21:29 UTC, codinglikeagirl42 commented on content/assignments/techjobs-console/task-three/index.md
> +chapter on [Data Types]().
Please update link

2023-05-25 21:32 UTC, codinglikeagirl42 commented on content/assignments/techjobs-console/_index.md
> +originalAuthorGitHub: gildedgardenia # to be set by page creator
```suggestion
originalAuthor: John Woolbright # to be set by page creator
originalAuthorGitHub: jwoolbright23 # to be set by page creator
```

2023-05-25 21:33 UTC, codinglikeagirl42 commented on content/assignments/techjobs-console/submission/index.md
> +originalAuthorGitHub: gildedgardenia # to be set by page creator
```suggestion
originalAuthor: John Woolbright # to be set by page creator
originalAuthorGitHub: jwoolbright23 # to be set by page creator
```

2023-05-25 21:34 UTC, codinglikeagirl42 commented on content/assignments/techjobs-console/task-three/index.md
> +originalAuthorGitHub: gildedgardenia # to be set by page creator
```suggestion
originalAuthor: John Woolbright # to be set by page creator
originalAuthorGitHub: jwoolbright23 # to be set by page creator
```

2023-05-25 21:35 UTC, codinglikeagirl42 commented on content/assignments/techjobs-console/task-three/index.md
> +lastMod: # UPDATE ANY TIME CHANGES ARE MADE
If Sally created the page - please update lines 10 -12 accordingly

2023-05-25 21:37 UTC, codinglikeagirl42 commented on content/assignments/_index.md
> +lastMod: 2023-02-07  # UPDATE ANY TIME CHANGES ARE MADE
```suggestion
lastEditor:  # update any time edits are made after review
lastEditorGitHub:  # update any time edits are made after review
lastMod:   # UPDATE ANY TIME CHANGES ARE MADE
```

2023-05-25 21:37 UTC, codinglikeagirl42 commented on content/assignments/techjobs-console/_index.md
> +lastMod: # UPDATE ANY TIME CHANGES ARE MADE
If Sally created the page - please update lines 10 -12 accordingly

2023-05-25 21:39 UTC, codinglikeagirl42 commented on content/assignments/techjobs-console/submission/index.md
> +lastMod: # UPDATE ANY TIME CHANGES ARE MADE
If Sally created the page - please update lines 10 -12 accordingly

2023-05-25 21:41 UTC, codinglikeagirl42 requested changes
Initial review - Metadata updates and link updates needed.  May need additional instructions when opening starter code depending on instructions and setup / assignment 0 review, which has not been submitted yet.

2023-06-06 19:47 UTC, codinglikeagirl42 commented on content/assignments/techjobs-console/_index.md
> +or more of the [bonus missions](#tech-jobs-console-bonus-missions).
Link still doesn't work -> notice that you are using a different syntax for internal book links than Courtney and Sally.  See: https://raw.githubusercontent.com/LaunchCodeEducation/csharp-web-dev-curriculum/main/content/assignments/tech-jobs-oo/_index.md

2023-06-06 19:58 UTC, codinglikeagirl42 commented on content/assignments/techjobs-console/_index.md
> +In Canvas, **Graded Assignment #1: TechJobs Console** contains a GitHub Classroom assignment invitation link and then set up the project in IntelliJ. Refer back to the GitHub Classroom instructions f
Not sure if this link will be an issue once merged into main, as it seems to be hard coded instead of using relref, see above comment.

2023-06-06 20:03 UTC, codinglikeagirl42 commented on content/assignments/techjobs-console/submission/index.md
> +[submission instructions]().
Still getting 404 error.

2023-06-06 20:39 UTC, codinglikeagirl42 requested changes
Second review completed, please see comments.  If you have any questions please let me know.

2023-06-08 20:19 UTC, icr8FreeCode approved these changes
New pages changes. Did not verify links. Please ensure all links are working once merged @jwoolbright23

2023-06-08 20:46 UTC, merged